# Generated by Django 6.0.7 on 2026-09-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_job_jobvacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobVacancy',
        ),
    ]
