# Generated by Django 6.0.7 on 2026-09-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0011_alter_candidatejobpreference_maximum_salary_and_more'),
        ('company_app', '0005_job_closed_at_job_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_resume', models.FileField(upload_to='candidate/application_resumes/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('AI_INTERVIEW', 'AI Interview'), ('CLASSIFIED', 'Classified'), ('SELECTED', 'Selected'), ('FINAL_INTERVIEW', 'Final Interview'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='candidate_app.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company_app.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
