# Generated by Django 6.0.7 on 2026-09-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResumeScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField()),
                ('skills_score', models.PositiveIntegerField()),
                ('experience_score', models.PositiveIntegerField()),
                ('education_score', models.PositiveIntegerField()),
                ('recommendation', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_screening', to='company_app.jobapplication')),
            ],
        ),
    ]
