# Generated by Django 6.0.7 on 2026-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_airesumescreening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RESUME_SCREENING', 'Resume Screening'), ('SHORTLISTED', 'Shortlisted'), ('AI_INTERVIEW', 'AI Interview'), ('SELECTED', 'Selected'), ('FINAL_INTERVIEW', 'Final Interview'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30),
        ),
    ]
