# Generated by Django 6.0.7 on 2026-07-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('SSLC', 'SSLC'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('CERTIFICATION', 'Certification')], max_length=30)),
                ('institution_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidate_app.candidateprofile')),
            ],
        ),
    ]
