# Generated by Django 6.0.7 on 2026-07-31 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0004_skill_rename_grade_candidateeducation_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateeducation',
            old_name='candidate',
            new_name='candidate_profile',
        ),
        migrations.RenameField(
            model_name='candidateexperience',
            old_name='candidate',
            new_name='candidate_profile',
        ),
        migrations.RenameField(
            model_name='candidateskill',
            old_name='candidate',
            new_name='candidate_profile',
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate_profile', 'skill')},
        ),
        migrations.CreateModel(
            name='CandidateJobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_job_role', models.CharField(max_length=255)),
                ('preferred_locations', models.JSONField(default=list)),
                ('minimum_salary', models.PositiveIntegerField()),
                ('maximum_salary', models.PositiveIntegerField()),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20)),
                ('remote_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to='candidate_app.candidateprofile')),
            ],
        ),
    ]
