# Generated by Django 6.0.7 on 2026-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0005_rename_candidate_candidateeducation_candidate_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
