# Generated by Django 6.0.7 on 2026-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0006_alter_candidateeducation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
