# Generated by Django 6.0.7 on 2026-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0007_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
