# Generated by Django 6.0.7 on 2026-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0008_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobpreference',
            name='maximum_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatejobpreference',
            name='minimum_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
