# Generated by Django 6.0.7 on 2026-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0009_alter_candidatejobpreference_maximum_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobpreference',
            name='maximum_salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatejobpreference',
            name='minimum_salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
