# Generated by Django 6.0.7 on 2026-09-21 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0011_alter_candidatejobpreference_maximum_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RESUME_SCREENING_COMPLETED', 'Resume Screening Completed'), ('AI_INTERVIEW_SCHEDULED', 'AI Interview Scheduled'), ('AI_INTERVIEW_REMINDER', 'AI Interview Reminder'), ('AI_INTERVIEW_COMPLETED', 'AI Interview Completed'), ('AI_INTERVIEW_REPORT', 'AI Interview Report Available'), ('AI_INTERVIEW_RESULT', 'AI Interview Result')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
