# Generated by Django 6.0.7 on 2026-09-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0012_notification'),
        ('company_app', '0009_aiinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('THEORY', 'Theory'), ('CODING', 'Coding')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('question_order', models.PositiveIntegerField()),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='company_app.aiinterview')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('interview', 'question_order')},
            },
        ),
        migrations.CreateModel(
            name='AIInterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveIntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='candidate_app.aiinterviewquestion')),
            ],
        ),
    ]
