# Generated by Django 6.0.7 on 2026-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0013_aiinterviewquestion_aiinterviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewquestion',
            name='programming_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aiinterviewquestion',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
