# Generated by Django 6.0.7 on 2026-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0014_aiinterviewquestion_programming_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewanswer',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='candidate/ai_interview_answers/'),
        ),
    ]
