# Generated by Django 6.0.7 on 2026-09-24 11:12

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0015_aiinterviewanswer_audio_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterviewanswer',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, storage=core.storages.AudioCloudinaryStorage(), upload_to='candidate/ai_interview_answers/'),
        ),
    ]
